solution:
  misc:
    - C:
      - -std=c99
      - -Og
      - -fdata-sections
    - Link:
      - --specs=nosys.specs
      - --entry=Reset_Handler
      - -Wl,-Map=.map,--cref,-print-memory-usage,--gc-sections,--no-warn-rwx-segments
        # generate linker map
        # output a cross reference table
        # print memory usage to console
        # exclude unused sections from the iamge
        # suppress executable write segment warnings (used for ITCM)
  projects:
    - project: .cproject.yaml
  target-types:
    - device: Alif Semiconductor::AE722F80F55D5AE:M55_HE
      type: HE
      compiler: GCC
      debug: "on"
      define:
        - "CORE_M55_HE"
    - device: Alif Semiconductor::AE722F80F55D5AE:M55_HP
      type: HP
      compiler: GCC
      debug: "on"
      define:
        - "CORE_M55_HP"